image: "python:3.8" 

job:
  tags:
    - use1-ci-builder-20

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis

pylint:
  stage: Static Analysis
  script:
    - pylint -d duplicate-code -d invalid-name sdb
