image: "python:3.8" 


before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis

pylint:
  stage: Static Analysis
  script:
    - pylint -d duplicate-code -d invalid-name sdb
