on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'

jobs:
  sync:
    strategy:
      matrix:
        branch:
          - 6.0/stage
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: delphix/actions/sync-with-master@master
        with:
          branch-to-sync: ${{ matrix.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
